import { Aspect, Indicator } from "./types";

export const ASPECTS: Aspect[] = [
  {
    id: "religion_moral",
    name: "Nilai Agama dan Moral",
    indicators: [
      { id: "rm_01", text: "Mengetahui agama yang dianutnya" },
      { id: "rm_02", text: "Meniru gerakan ibadah dengan urutan yang benar" },
      { id: "rm_03", text: "Mengucapkan doa sebelum dan/atau sesudah melakukan kegiatan" },
      { id: "rm_04", text: "Mengenal perilaku baik/sopan dan buruk" },
      { id: "rm_05", text: "Membiasakan diri berprilaku baik" },
      { id: "rm_06", text: "Mengucapkan salam dan membalas salam" },
      { id: "rm_07", text: "Menghormati orang yang lebih tua" },
      { id: "rm_08", text: "Mengenal hari-hari besar agama" },
      { id: "rm_09", text: "Menjaga kebersihan diri" },
      { id: "rm_10", text: "Menyayangi sesama makhluk ciptaan Tuhan" },
      { id: "rm_11", text: "Sabar menunggu giliran" },
      { id: "rm_12", text: "Menghargai perbedaan teman" },
      { id: "rm_13", text: "Mau berbagi dengan teman" },
      { id: "rm_14", text: "Berbicara santun kepada siapa saja" },
      { id: "rm_15", text: "Membantu teman yang membutuhkan" },
      { id: "rm_16", text: "Menjaga lingkungan sekitar" },
      { id: "rm_17", text: "Berani mengakui kesalahan" },
      { id: "rm_18", text: "Meminta maaf jika bersalah" },
      { id: "rm_19", text: "Mengucapkan terima kasih" },
      { id: "rm_20", text: "Menjalankan aturan di kelas" },
    ],
  },
  {
    id: "physical_motor",
    name: "Fisik Motorik",
    indicators: [
      { id: "pm_01", text: "Melakukan gerakan tubuh secara terkoordinasi (berlari)" },
      { id: "pm_02", text: "Melakukan gerakan melompat dan meloncat" },
      { id: "pm_03", text: "Memanjat dan bergelantungan dengan aman" },
      { id: "pm_04", text: "Menangkap bola dengan tepat" },
      { id: "pm_05", text: "Melempar bola ke arah sasaran" },
      { id: "pm_06", text: "Menjaga keseimbangan saat berjalan di papan titian" },
      { id: "pm_07", text: "Menendang bola dengan terarah" },
      { id: "pm_08", text: "Melakukan gerakan ziz-zag" },
      { id: "pm_09", text: "Merayap dan merangkak dengan lancar" },
      { id: "pm_10", text: "Menggerakkan jari tangan untuk kelenturan (meremas)" },
      { id: "pm_11", text: "Menggunakan alat tulis dengan benar" },
      { id: "pm_12", text: "Menggunting sesuai dengan pola" },
      { id: "pm_13", text: "Menempel gambar dengan rapi" },
      { id: "pm_14", text: "Melipat kertas secara sederhana" },
      { id: "pm_15", text: "Meronce dengan benang dan manik-manik" },
      { id: "pm_16", text: "Mencuci tangan dengan sabun secara mandiri" },
      { id: "pm_17", text: "Makan dan minum sendiri dengan rapi" },
      { id: "pm_18", text: "Mampu memakai sepatu dan baju sendiri" },
      { id: "pm_19", text: "Membuang sampah pada tempatnya" },
      { id: "pm_20", text: "Membersihkan peralatan setelah bermain" },
    ],
  },
  {
    id: "cognitive",
    name: "Kognitif",
    indicators: [
      { id: "cg_01", text: "Mengenal perbedaan berdasarkan ukuran (besar-kecil)" },
      { id: "cg_02", text: "Mengurutkan benda berdasarkan tinggi-rendah" },
      { id: "cg_03", text: "Mengenal bentuk geometri (lingkaran, segitiga, persegi)" },
      { id: "cg_04", text: "Mengelompokkan benda berdasarkan warna" },
      { id: "cg_05", text: "Membilang angka 1 sampai 20" },
      { id: "cg_06", text: "Menghubungkan lambang bilangan dengan benda" },
      { id: "cg_07", text: "Mengenal konsep waktu (pagi, siang, malam)" },
      { id: "cg_08", text: "Membedakan benda yang berat dan ringan" },
      { id: "cg_09", text: "Menyusun puzzle sederhana" },
      { id: "cg_10", text: "Mengenal pola warna (merah-biru-merah-biru)" },
      { id: "cg_11", text: "Memahami instruksi dua langkah" },
      { id: "cg_12", text: "Mampu memecahkan masalah sederhana" },
      { id: "cg_13", text: "Mengenal fungsi benda-benda di sekitar" },
      { id: "cg_14", text: "Mengetahui hubungan sebab-akibat sederhana" },
      { id: "cg_15", text: "Mengenal gejala alam (hujan, pelangi)" },
      { id: "cg_16", text: "Mengenal bagian-bagian tubuh" },
      { id: "cg_17", text: "Mengenal habitat hewan sederhana" },
      { id: "cg_18", text: "Menyebutkan nama-nama tanaman" },
      { id: "cg_19", text: "Mengenal alat transportasi" },
      { id: "cg_20", text: "Hafal alamat rumah atau nama orang tua" },
    ],
  },
];

export const SCALE_LABELS: Record<string, string> = {
  BB: "Belum Berkembang",
  MB: "Mulai Berkembang",
  BSH: "Sesuai Harapan",
  BSB: "Sangat Baik",
};

export const SCALE_COLORS: Record<string, string> = {
  BB: "bg-red-500/80",
  MB: "bg-orange-500/80",
  BSH: "bg-emerald-500/80",
  BSB: "bg-blue-500/80",
};

export const CURRICULUM_INDICATORS: Indicator[] = [
  { id: "curr_01", text: "Menunjukkan kemandirian dalam kegiatan rutin di sekolah" },
  { id: "curr_02", text: "Mampu bekerja sama dalam kelompok kecil saat bermain" },
  { id: "curr_03", text: "Menunjukkan rasa percaya diri saat tampil di depan kelas" },
  { id: "curr_04", text: "Mengenal dan mematuhi aturan serta tata tertib sekolah" },
  { id: "curr_05", text: "Mampu mengekspresikan emosi dengan cara yang tepat" },
  { id: "curr_06", text: "Menunjukkan minat dalam kegiatan seni dan kreativitas" },
  { id: "curr_07", text: "Merespons instruksi guru dengan cepat dan benar" },
  { id: "curr_08", text: "Peduli terhadap kebersihan lingkungan sekolah" },
  { id: "curr_09", text: "Berani mencoba hal-hal baru yang positif" },
  { id: "curr_10", text: "Menunjukkan sikap santun kepada guru dan karyawan sekolah" },
];

export const AUDIT_PIN = "2026";
